---
# tasks file for wordpress
- name: Baixa o wordpress
  get_url:
     url=https://wordpress.org/latest.tar.gz
     dest=/tmp/wordpress.tar.gz
     validate_certs=no

- name: Descompacta o Wordpress
  unarchive: 
     src=/tmp/wordpress.tar.gz 
     dest=/var/www/ copy=no

- name: Atualiza o site Apache padrao
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
       regexp="(.)+DocumentRoot /var/www/html"
       line="DocumentRoot /var/www/wordpress"

  notify:
  - reinicia_apache


    #- name: Renomeia o arquivo de configuracao exemplo
    #command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

  #Vou testar o que foi feito ate aqui, senao depois a gente fica igual doido debugando, kkk
